services:
  db:
    image: mysql
    container_name: database
    env_file:
      - ./db/.env
    ports:
      - 3308:3306
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    networks:
      - app-network
  admin:
    container_name: admin_frontend
    build:
      context: ./frontend/admin
      dockerfile: dev.Dockerfile
      target: dev
    restart: always
    env_file:
      - ./frontend/admin/.env
    depends_on:
      - backend
    volumes:
      - ./frontend/admin:/app
      - /app/node_modules
    ports:
      - 5173:5173
    networks:
      - app-network

  client:
    container_name: client_frontend
    build:
      context: ./frontend/client
      dockerfile: dev.Dockerfile
      target: dev
    restart: always
    env_file:
      - ./frontend/client/.env
    depends_on:
      - backend
    volumes:
      - ./frontend/client:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
