services:
  admin:
    container_name: admin-app
    build:
      context: .
      dockerfile: dev.Dockerfile
      target: dev
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
